import mongoose from 'mongoose';
import { mongoDBURL } from '../config.js';
import Book from '../models/bookmodels.js';

const seedBooks = [
  {
    title: 'The Silent Cipher',
    author: 'Nina Hale',
    description: 'A fast-paced mystery about a journalist uncovering a decades-old secret network.',
    genre: 'Mystery',
    tags: ['investigation', 'thriller', 'fast-paced'],
    themes: ['truth', 'betrayal'],
    subjects: ['journalism', 'crime'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2022-04-11'),
    price: 240,
    rating: 4.5,
    isPublished: true,
  },
  {
    title: 'Summer at Fern Lake',
    author: 'Iris Moore',
    description: 'A warm contemporary romance set in a quiet lakeside town.',
    genre: 'Romance',
    tags: ['small-town', 'feel-good'],
    themes: ['healing', 'second chances'],
    subjects: ['relationships'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2021-06-20'),
    price: 210,
    rating: 4.1,
    isPublished: true,
  },
  {
    title: 'Orbit of Ashes',
    author: 'K. R. Solis',
    description: 'A political science fiction epic where factions battle for control of a dying star system.',
    genre: 'Science Fiction',
    tags: ['space opera', 'epic'],
    themes: ['power', 'survival'],
    subjects: ['space', 'politics'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2020-09-01'),
    price: 320,
    rating: 4.7,
    isPublished: true,
  },
  {
    title: 'Tiny Giants of the Forest',
    author: 'Leah Ponce',
    description: 'An illustrated nature book introducing children to insects and forest ecosystems.',
    genre: 'Educational',
    tags: ['nature', 'illustrated', 'kids'],
    themes: ['curiosity', 'environment'],
    subjects: ['biology', 'ecology'],
    language: 'English',
    audience: 'Kids',
    publishedDate: new Date('2019-03-14'),
    price: 230,
    rating: 4.2,
    isPublished: true,
  },
  {
    title: 'Monsoon Kitchens',
    author: 'Arjun Patel',
    description: 'A regional cookbook featuring affordable recipes and quick weeknight meals.',
    genre: 'Cooking',
    tags: ['budget', 'quick meals'],
    themes: ['family', 'culture'],
    subjects: ['food', 'home cooking'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-01-10'),
    price: 260,
    rating: 4.0,
    isPublished: true,
  },
  {
    title: 'The Paper Crown',
    author: 'Elena Voss',
    description: 'A sweeping fantasy about rival heirs fighting for a kingdom built on ancient contracts.',
    genre: 'Fantasy',
    tags: ['court intrigue', 'magic'],
    themes: ['legacy', 'loyalty'],
    subjects: ['kingdoms', 'myth'],
    language: 'English',
    audience: 'Young Adult',
    publishedDate: new Date('2024-02-09'),
    price: 350,
    rating: 4.6,
    isPublished: true,
  },
  {
    title: 'Before the Bell Rings',
    author: 'Marta Diaz',
    description: 'A practical guide for students to build habits, confidence, and exam routines.',
    genre: 'Self Help',
    tags: ['study skills', 'productivity'],
    themes: ['discipline', 'growth'],
    subjects: ['education', 'habits'],
    language: 'English',
    audience: 'Teen',
    publishedDate: new Date('2022-08-18'),
    price: 220,
    rating: 3.9,
    isPublished: true,
  },
  {
    title: 'Echoes in Red Clay',
    author: 'Jonah Reed',
    description: 'Historical fiction following three generations in a changing rural community.',
    genre: 'Historical Fiction',
    tags: ['multi-generational', 'character-driven'],
    themes: ['identity', 'migration'],
    subjects: ['history', 'community'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2018-11-02'),
    price: 280,
    rating: 4.3,
    isPublished: true,
  },
  {
    title: 'Night Shift Protocol',
    author: 'Ava Brooks',
    description: 'A techno-thriller where a cybersecurity analyst races to stop a coordinated blackout.',
    genre: 'Thriller',
    tags: ['cybersecurity', 'high-stakes'],
    themes: ['risk', 'responsibility'],
    subjects: ['technology', 'crime'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-07-07'),
    price: 310,
    rating: 4.4,
    isPublished: true,
  },
  {
    title: 'Whispers Under Lantern Light',
    author: 'C. J. Navarro',
    description: 'A poetic literary novel about memory, art, and friendship in an old harbor city.',
    synopsis: 'A lyrical story about an archivist and a painter whose friendship helps them confront old grief, lost letters, and the meaning of home.',
    genre: 'Literary Fiction',
    tags: ['slow-burn', 'atmospheric'],
    themes: ['memory', 'belonging'],
    subjects: ['art', 'city life'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2020-01-28'),
    price: 390,
    rating: 4.8,
    isPublished: true,
  },
  {
    title: 'Saltwater Letters',
    author: 'Mina Rahman',
    description: 'An intimate family drama about migration, inheritance, and the letters that survive generations.',
    synopsis: 'A daughter returns to her coastal hometown to settle her mother’s estate and uncovers a trail of letters that reveal family sacrifices, lost love, and the cost of leaving home.',
    genre: 'Drama',
    tags: ['family saga', 'emotional'],
    themes: ['migration', 'memory'],
    subjects: ['family', 'history'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2022-12-14'),
    price: 340,
    rating: 4.5,
    isPublished: true,
  },
  {
    title: 'Midnight Atlas',
    author: 'R. E. Khan',
    description: 'A globe-trotting adventure following a cartographer chasing a hidden route through forgotten cities.',
    synopsis: 'When a mapmaker inherits an atlas with missing pages, she follows cryptic clues across three continents to find a lost route, a vanished expedition, and a truth that could rewrite history.',
    genre: 'Adventure',
    tags: ['travel', 'quest'],
    themes: ['discovery', 'courage'],
    subjects: ['maps', 'history'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-05-03'),
    price: 420,
    rating: 4.6,
    isPublished: true,
  },
  {
    title: 'Neon Verdict',
    author: 'Tasha Grant',
    description: 'A legal thriller about a public defender pulled into a case involving corrupt surveillance tech.',
    synopsis: 'A public defender takes on an impossible case when a whistleblower is framed using citywide surveillance data, forcing her to choose between the law, the truth, and her own safety.',
    genre: 'Thriller',
    tags: ['legal', 'surveillance'],
    themes: ['justice', 'corruption'],
    subjects: ['law', 'technology'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-10-21'),
    price: 300,
    rating: 4.2,
    isPublished: true,
  },
  {
    title: 'The Moon Jar Market',
    author: 'Saeed Alam',
    description: 'A cozy fantasy about a hidden marketplace that appears only under moonlight.',
    synopsis: 'A baker stumbles into a magical night market where jars contain weather, memories, and tiny miracles, but every purchase has a price that changes the town forever.',
    genre: 'Fantasy',
    tags: ['cozy', 'magical'],
    themes: ['wonder', 'community'],
    subjects: ['magic', 'market'],
    language: 'English',
    audience: 'Young Adult',
    publishedDate: new Date('2021-11-09'),
    price: 275,
    rating: 4.7,
    isPublished: true,
  },
  {
    title: 'Stillness for Busy Minds',
    author: 'Dr. Lina Chowdhury',
    description: 'A practical mindfulness book for readers who want short exercises and calm routines.',
    synopsis: 'A compassionate, science-informed guide that breaks mindfulness into brief daily practices for stressed readers who want calmer mornings, better focus, and less mental clutter.',
    genre: 'Self Help',
    tags: ['mindfulness', 'short reads'],
    themes: ['calm', 'routine'],
    subjects: ['wellbeing', 'habits'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2020-04-16'),
    price: 200,
    rating: 4.1,
    isPublished: true,
  },
];

const run = async () => {
  try {
    await mongoose.connect(mongoDBURL);

    for (const seedBook of seedBooks) {
      const seedRecord = {
        ...seedBook,
        synopsis: seedBook.synopsis || seedBook.description || '',
      };

      await Book.findOneAndUpdate(
        { title: seedRecord.title, author: seedRecord.author },
        seedRecord,
        {
          returnDocument: 'after',
          upsert: true,
          runValidators: true,
          setDefaultsOnInsert: true,
        }
      );
    }

    console.log(`Seed completed: ${seedBooks.length} books upserted.`);
  } catch (error) {
    console.error('Seed failed:', error.message);
    process.exitCode = 1;
  } finally {
    await mongoose.disconnect();
  }
};

run();
