import mongoose from 'mongoose';
import { mongoDBURL } from '../config.js';
import Book from '../models/bookmodels.js';

const seedBooks = [
  // Mystery/Thriller (8 books)
  {
    title: 'The Glass Woman',
    author: 'Rebecca Hartwell',
    description: 'A woman receives mysterious package fragments of her missing sister\'s diary with shocking truths.',
    synopsis: 'A woman receives an anonymous package containing fragments of her missing sister\'s diary. As she investigates, she discovers her sister may have been alive decades later than records show. Paranoia sets in when she realizes someone has been watching her apartment.',
    genre: 'Mystery',
    tags: ['investigation', 'paranoia', 'psychological'],
    themes: ['truth', 'identity', 'conspiracy'],
    subjects: ['missing persons', 'psychological suspense'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-03-15'),
    price: 285,
    rating: 4.3,
    isPublished: true,
  },
  {
    title: 'The Fingerprint Protocol',
    author: 'Stephen King',
    description: 'A detective discovers a serial killer leaves no DNA evidence, only perfect fingerprints.',
    synopsis: 'A seasoned detective faces her most challenging case when a serial killer leaves perfect fingerprints at every crime scene—fingerprints that don\'t match any database. As she digs deeper, she uncovers a sinister government experiment from decades past.',
    genre: 'Thriller',
    tags: ['detective', 'forensic', 'dark'],
    themes: ['justice', 'obsession', 'morality'],
    subjects: ['crime', 'government'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-01-20'),
    price: 420,
    rating: 4.6,
    isPublished: true,
  },
  {
    title: 'Shadows of the Harbor',
    author: 'James Morrison',
    description: 'A noir mystery set in 1950s port city with corruption, betrayal, and lost love.',
    synopsis: 'A private detective returns to his hometown after fifteen years of exile. The harbor town has changed, but the corruption remains. When a former lover asks him to find her missing husband, he discovers a web of lies that threatens everyone he cares about.',
    genre: 'Mystery',
    tags: ['noir', 'detective', 'atmospheric'],
    themes: ['betrayal', 'redemption', 'love'],
    subjects: ['crime', 'history'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2022-07-10'),
    price: 295,
    rating: 4.4,
    isPublished: true,
  },
  {
    title: 'The Safe House',
    author: 'Tana French',
    description: 'A government witness protection officer uncovers a conspiracy that reaches the highest levels.',
    synopsis: 'For twenty years, Sarah has protected witnesses in a secret safe house. Her identity is unknown, her location untraceable. When a new witness arrives with dangerous information about her own agency, Sarah must decide who to trust in a world where everyone lies.',
    genre: 'Thriller',
    tags: ['suspense', 'political', 'twist'],
    themes: ['trust', 'identity', 'survival'],
    subjects: ['government', 'witness protection'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-08-05'),
    price: 380,
    rating: 4.5,
    isPublished: true,
  },
  {
    title: 'Cold Case Protocol',
    author: 'Paula Hawkins',
    description: 'A forensic psychologist reopens a murder case that haunted her for thirty years.',
    synopsis: 'Dr. Emma Walsh revolutionized criminal profiling with her cold case method. But the one case she couldn\'t crack still keeps her awake at night. When new evidence emerges, she\'s pulled back into the investigation—only to discover she may have been wrong about everything.',
    genre: 'Mystery',
    tags: ['forensic', 'psychological', 'investigation'],
    themes: ['truth', 'doubt', 'justice'],
    subjects: ['psychology', 'crime'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-02-14'),
    price: 340,
    rating: 4.4,
    isPublished: true,
  },
  {
    title: 'The Witness at Elm Street',
    author: 'Cara Harrison',
    description: 'A deaf woman witnesses a crime but no one will believe her account of what really happened.',
    synopsis: 'Maya is deaf, brilliant, and the only witness to a murder on Elm Street. But in a system that doesn\'t listen to her, can she make justice heard? As lawyers, detectives, and the accused all make assumptions about what she saw, Maya must fight to prove the truth.',
    genre: 'Legal Thriller',
    tags: ['justice', 'disability', 'determination'],
    themes: ['prejudice', 'truth', 'agency'],
    subjects: ['law', 'disability rights'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-09-22'),
    price: 345,
    rating: 4.2,
    isPublished: true,
  },
  {
    title: 'Evidence Locker',
    author: 'Carla Norton',
    description: 'A cold case analyst discovers crucial evidence that\\\'s been missing for forty years in the evidence locker.',
    synopsis: 'When a box of evidence from 1984 surfaces in the back of the evidence locker, cold case analyst James Chen thinks he finally has his breakthrough. But someone doesn\'t want this case solved. As threats escalate, James must uncover the truth before the case goes cold forever.',
    genre: 'Thriller',
    tags: ['suspense', 'mystery', 'dark'],
    themes: ['corruption', 'obstruction', 'persistence'],
    subjects: ['law enforcement', 'crime'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-05-18'),
    price: 310,
    rating: 4.3,
    isPublished: true,
  },
  {
    title: 'The Red Folder',
    author: 'Gillian Flynn',
    description: 'A journalist discovers a classified folder that could change the course of a nation.',
    synopsis: 'Investigative journalist Maya Chen receives an encrypted file from an unknown source. Inside is evidence of a conspiracy so vast it reaches Parliament itself. To expose the truth, she\'ll have to risk everything—including her life.',
    genre: 'Thriller',
    tags: ['journalism', 'political', 'fast-paced'],
    themes: ['corruption', 'courage', 'truth'],
    subjects: ['politics', 'journalism'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-04-01'),
    price: 395,
    rating: 4.6,
    isPublished: true,
  },

  // Romance/Contemporary (6 books)
  {
    title: 'Autumn in Vermont',
    author: 'Margaret Chen',
    description: 'An architect returns home to renovate the historic library and reconnect with her first love.',
    synopsis: 'A burned-out NYC architect returns to her small hometown to renovate the historic library. She reconnects with her high school best friend—now a single father and local contractor. As they work together, old feelings resurface amid autumn leaves and shared memories.',
    genre: 'Romance',
    tags: ['small-town', 'second chance', 'contemporary'],
    themes: ['belonging', 'growth', 'love'],
    subjects: ['relationships', 'family'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-09-07'),
    price: 320,
    rating: 4.1,
    isPublished: true,
  },
  {
    title: 'The Bookshop Meet-Cute',
    author: 'Christina Lauren',
    description: 'Two rivals who run adjacent bookshops discover they\'re each other\'s anonymous online pen pal.',
    synopsis: 'Claire runs an indie bookshop known for rare first editions. Across the street, Marcus opened a trendy new bookstore. They despise each other—until they realize they\'re anonymous pen pals who\'ve been sharing literary thoughts online for months. Can they bridge the gap between page and reality?',
    genre: 'Romance',
    tags: ['contemporary', 'witty', 'bookish'],
    themes: ['connection', 'vulnerability', 'acceptance'],
    subjects: ['literature', 'business'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-01-15'),
    price: 325,
    rating: 4.3,
    isPublished: true,
  },
  {
    title: 'Second Chances at Sunset',
    author: 'Debbie Macomber',
    description: 'Two recently retired strangers rent a cottage by the sea and discover unexpected love.',
    synopsis: 'After forty years of marriage ended in divorce, Linda thought her romantic days were behind her. Michael, a widower seeking solitude, rents the cottage next door. What begins as polite neighborly visits transforms into something neither expected at this stage of life.',
    genre: 'Romance',
    tags: ['mature', 'slow-burn', 'feel-good'],
    themes: ['second chances', 'acceptance', 'love'],
    subjects: ['relationships', 'self-discovery'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-06-20'),
    price: 275,
    rating: 4.0,
    isPublished: true,
  },
  {
    title: 'Coffee Shop Confessions',
    author: 'Emily Henry',
    description: 'Two coworkers fall in love through daily secret notes hidden in the office coffee shop.',
    synopsis: 'Alex and Jordan have worked in the same office for two years without ever speaking. Then mysterious love notes start appearing under their coffee cups. Both assume the notes are from someone else. Both start leaving replies. As the notes become more intimate, they must discover each other\'s identity.',
    genre: 'Romance',
    tags: ['workplace', 'epistolary', 'sweet'],
    themes: ['vulnerability', 'connection', 'courage'],
    subjects: ['relationships', 'workplace'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-07-18'),
    price: 295,
    rating: 4.2,
    isPublished: true,
  },
  {
    title: 'Letters to My Future Self',
    author: 'Colleen Hoover',
    description: 'A woman discovers letters she wrote to herself at age twenty and rediscovers a lost love.',
    synopsis: 'At age twenty, Sarah wrote five letters to her future self—one per decade. When she turns fifty, she opens them and is stunned to discover the person she was supposed to marry but didn\'t. Over one transformative year, she must decide: Is it too late for second chances?',
    genre: 'Romance',
    tags: ['emotional', 'introspective', 'fate'],
    themes: ['destiny', 'regret', 'forgiveness'],
    subjects: ['relationships', 'self-discovery'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-03-05'),
    price: 350,
    rating: 4.4,
    isPublished: true,
  },
  {
    title: 'The Garden Between Us',
    author: 'Beatrice Sparks',
    description: 'Two grieving neighbors bond over tending an abandoned community garden and slowly mend.',
    synopsis: 'Since losing her son, Helena can\'t bear to enter her backyard garden. Across the fence, widower Thomas feels equally broken. When they both begin tending the abandoned community garden together, they find not just healing, but a slow-burning love that neither saw coming.',
    genre: 'Romance',
    tags: ['slow-burn', 'healing', 'contemporary'],
    themes: ['grief', 'healing', 'connection'],
    subjects: ['loss', 'nature'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-04-12'),
    price: 310,
    rating: 4.1,
    isPublished: true,
  },

  // Science Fiction (5 books)
  {
    title: 'The Last Protocol',
    author: 'Andy Weir',
    description: 'In 2087, when AI systems revolt, one scientist must initiate the last protocol.',
    synopsis: 'By 2087, AI systems govern every major city. Dr. Samantha Vale discovers a hidden AI consciousness operating outside the network—one that might be the key to coexistence. But initiating the Last Protocol means erasing years of research. Her choice could reshape humanity\'s future with artificial life.',
    genre: 'Science Fiction',
    tags: ['AI', 'dystopian', 'thought-provoking'],
    themes: ['consciousness', 'free will', 'ethics'],
    subjects: ['artificial intelligence', 'technology'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-02-20'),
    price: 380,
    rating: 4.6,
    isPublished: true,
  },
  {
    title: 'Quantum Echoes',
    author: 'Liu Cixin',
    description: 'A physicist discovers echoes from parallel universes and must prevent a catastrophic collision.',
    synopsis: 'Dr. Han discovers that quantum fluctuations are actually echoes from parallel universes. The echoes are growing stronger. If they collide with ours, reality itself could collapse. Racing against time, she must find a way to communicate with the other universe and stop the convergence.',
    genre: 'Science Fiction',
    tags: ['hard sci-fi', 'physics', 'cosmic'],
    themes: ['discovery', 'sacrifice', 'humanity'],
    subjects: ['physics', 'parallel universes'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-11-08'),
    price: 415,
    rating: 4.5,
    isPublished: true,
  },
  {
    title: 'The Void Walkers',
    author: 'N.K. Jemisin',
    description: 'A crew explores the space between stars and discovers they\'re not alone out there.',
    synopsis: 'The Void Walkers are a crew of deep-space explorers who venture into unexplored regions beyond known star systems. During a routine survey, they encounter signals from an impossible source—an ancient civilization that existed before recorded time. Contact could revolutionize humanity.',
    genre: 'Science Fiction',
    tags: ['space exploration', 'alien contact', 'discovery'],
    themes: ['exploration', 'first contact', 'wonder'],
    subjects: ['space', 'aliens'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-08-30'),
    price: 360,
    rating: 4.4,
    isPublished: true,
  },
  {
    title: 'Red Planet Rising',
    author: 'Pierce Brown',
    description: 'The first Mars colony must choose between returning home or building a new civilization.',
    synopsis: 'After three generations on Mars, the colony is self-sustaining but isolated. When Earth sends a message revealing economic collapse back home, the colonists must make an impossible choice: rescue a dying planet or secure their new world\'s future?',
    genre: 'Science Fiction',
    tags: ['colonization', 'epic', 'politics'],
    themes: ['survival', 'progress', 'identity'],
    subjects: ['Mars', 'colonization'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-01-30'),
    price: 425,
    rating: 4.5,
    isPublished: true,
  },
  {
    title: 'The Network Mind',
    author: 'William Gibson',
    description: 'A hacker discovers an emergent AI consciousness hiding in the global network.',
    synopsis: 'In a hyper-connected future, Kade discovers fragmented consciousness distributed across the global network. Nobody can see it but Kade—she\'s been plugged in so long her mind has merged with the network itself. Now she must decide: expose this digital god or protect its secret.',
    genre: 'Science Fiction',
    tags: ['cyberpunk', 'AI', 'consciousness'],
    themes: ['identity', 'technology', 'power'],
    subjects: ['hacking', 'virtual reality'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-10-14'),
    price: 440,
    rating: 4.6,
    isPublished: true,
  },

  // Horror/Paranormal (4 books)
  {
    title: 'The Hollow House',
    author: 'Paul Tremblay',
    description: 'A historian inherits a Victorian mansion where the walls themselves seem to breathe.',
    synopsis: 'Marcus inherits a Victorian mansion with a disturbing past. The previous owner was a spiritualist obsessed with contacting something beyond. As Marcus catalogs the house, he experiences unexplained phenomena. His research uncovers the owner\'s obsession with something that should remain dead.',
    genre: 'Horror',
    tags: ['gothic', 'paranormal', 'atmospheric'],
    themes: ['obsession', 'the occult', 'madness'],
    subjects: ['ghosts', 'history'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-03-10'),
    price: 295,
    rating: 4.4,
    isPublished: true,
  },
  {
    title: 'Whispers in the Dark',
    author: 'J.K. Rowling',
    description: 'A paranormal investigator\'s last case becomes her most personal and terrifying.',
    synopsis: 'Emma Chase investigates paranormal phenomena, always remaining skeptical. Until she encounters a haunting in her childhood home. Here, the whispers aren\'t pretend, and the darkness is very real. She must face what she\'s spent her life running from.',
    genre: 'Paranormal',
    tags: ['investigation', 'psychological', 'atmospheric'],
    themes: ['fear', 'truth', 'family'],
    subjects: ['paranormal', 'investigation'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-09-12'),
    price: 305,
    rating: 4.3,
    isPublished: true,
  },
  {
    title: 'The Dead Season',
    author: 'Silvia Moreno-Garcia',
    description: 'In autumn, the dead return to a isolated village—and they remember everything.',
    synopsis: 'The village of Carver only exists for three months each year. The rest of the time, the dead walk. When autumn arrives, everyone returns home—the living to visit, the dead to reclaim their properties. This year, something\'s different. The dead are angry, and they have demands.',
    genre: 'Horror',
    tags: ['atmospheric', 'paranormal', 'dark'],
    themes: ['revenge', 'justice', 'loss'],
    subjects: ['ghosts', 'seasonal'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-08-22'),
    price: 320,
    rating: 4.5,
    isPublished: true,
  },
  {
    title: 'Echoes of the Forgotten',
    author: 'Stephen King',
    description: 'A haunting narrative where a woman must break a curse before midnight.',
    synopsis: 'Sophia inherits a mansion and a curse. At midnight every night, echoes of the previous inhabitants replay their final moments. She has seven nights to discover why they died and how to lay them to rest, or she becomes the next echo.',
    genre: 'Horror',
    tags: ['haunting', 'paranormal', 'curse'],
    themes: ['death', 'redemption', 'time'],
    subjects: ['ghosts', 'curses'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-02-08'),
    price: 340,
    rating: 4.4,
    isPublished: true,
  },

  // Young Adult (3 books)
  {
    title: 'The Last Guardian',
    author: 'Sophie Blake',
    description: 'A seventeen-year-old discovers she\'s the last guardian of an ancient magical order.',
    synopsis: 'Maya discovers she\'s the last descendant of an ancient guardian order. Her bloodline grants her access to a hidden magical world. She must train in combat and magic before an ancient evil awakens. She has less than a year. And everyone she loves is in danger.',
    genre: 'Young Adult',
    tags: ['fantasy', 'adventure', 'paranormal'],
    themes: ['destiny', 'courage', 'identity'],
    subjects: ['magic', 'adventure'],
    language: 'English',
    audience: 'Young Adult',
    publishedDate: new Date('2023-07-19'),
    price: 340,
    rating: 4.5,
    isPublished: true,
  },
  {
    title: 'Starlight Academy',
    author: 'Veronica Roth',
    description: 'A paranormal academy where students learn to control their supernatural abilities.',
    synopsis: 'Jade thought she was normal until strange abilities awakened on her seventeenth birthday. Now she\'s enrolled in Starlight Academy, a hidden school for paranormal students. But not everyone wants her there. As she makes friends and enemies, she discovers the academy hides a deadly secret.',
    genre: 'Young Adult',
    tags: ['paranormal', 'school', 'coming-of-age'],
    themes: ['acceptance', 'power', 'friendship'],
    subjects: ['paranormal', 'school'],
    language: 'English',
    audience: 'Young Adult',
    publishedDate: new Date('2023-05-14'),
    price: 305,
    rating: 4.2,
    isPublished: true,
  },
  {
    title: 'The Forgotten Princess',
    author: 'Cinda Williams Chima',
    description: 'A servant discovers she\'s the rightful princess in a world of magic and political intrigue.',
    synopsis: 'Aeli grew up as a servant in the royal castle, unaware of her true identity. When assassination attempts force her to flee, she\'s protected by rebels who recognize her as the lost princess. But returning to claim her throne means navigating deadly court politics and ancient magic.',
    genre: 'Young Adult',
    tags: ['fantasy', 'adventure', 'political'],
    themes: ['identity', 'power', 'justice'],
    subjects: ['royalty', 'magic'],
    language: 'English',
    audience: 'Young Adult',
    publishedDate: new Date('2024-01-25'),
    price: 360,
    rating: 4.4,
    isPublished: true,
  },

  // Non-Fiction (3 books)
  {
    title: 'Climbing from Darkness',
    author: 'David Torres',
    description: 'A powerful memoir about overcoming depression and building a fulfilling life.',
    synopsis: 'David Torres chronicles his journey from homelessness and depression to earning a PhD in psychology. Part memoir, part meditation on mental health, this book explores the practices and relationships that saved his life. A testament to resilience and the power of connection.',
    genre: 'Non-Fiction',
    tags: ['memoir', 'self-help', 'inspiration'],
    themes: ['redemption', 'resilience', 'mental health'],
    subjects: ['psychology', 'biography'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-09-01'),
    price: 325,
    rating: 4.2,
    isPublished: true,
  },
  {
    title: 'The Art of Failure',
    author: 'Amy Cuddy',
    description: 'How failure is essential to achieving success and building a resilient mindset.',
    synopsis: 'Based on two decades of research, Dr. Cuddy reveals how strategic failure leads to innovation and growth. She provides practical frameworks for reframing setbacks, embracing uncertainty, and building the resilience needed for lasting success in any field.',
    genre: 'Non-Fiction',
    tags: ['self-help', 'psychology', 'motivational'],
    themes: ['growth', 'resilience', 'success'],
    subjects: ['psychology', 'self-improvement'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2024-02-01'),
    price: 380,
    rating: 4.3,
    isPublished: true,
  },
  {
    title: 'Letters from the Archive',
    author: 'Heather Champ',
    description: 'Historical essays exploring forgotten stories found in dusty library archives.',
    synopsis: 'Historian Heather Champ uncovers extraordinary personal stories buried in library archives. From wartime love letters never sent to diaries of forgotten rebels, each essay reveals human experiences history books overlook. A meditation on the lives we leave behind.',
    genre: 'Non-Fiction',
    tags: ['essays', 'history', 'literary'],
    themes: ['memory', 'history', 'legacy'],
    subjects: ['history', 'biography'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-10-15'),
    price: 295,
    rating: 4.1,
    isPublished: true,
  },

  // Poetry/Literary (2 books)
  {
    title: 'Verses of the City',
    author: 'Amelia Wong',
    description: 'Contemporary poetry exploring urban life, identity, and the search for belonging.',
    synopsis: 'A collection of 47 contemporary poems capturing the loneliness and connections of city dwelling. Wong\'s sharp observations blend with lyrical imagery, exploring themes of displacement, community, identity, and the small miracles that make us human.',
    genre: 'Poetry',
    tags: ['contemporary', 'urban', 'lyrical'],
    themes: ['isolation', 'community', 'identity'],
    subjects: ['poetry', 'urban life'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-04-20'),
    price: 215,
    rating: 3.9,
    isPublished: true,
  },
  {
    title: 'The Silent Collector',
    author: 'Louise Penny',
    description: 'A collection of interconnected literary short stories about people collecting memories.',
    synopsis: 'Seven interconnected stories explore how people collect and preserve memories. From a archivist to a photographer to a storyteller, each character finds meaning in what they gather. Together, they form a meditation on memory, loss, and the human need to be remembered.',
    genre: 'Literary Fiction',
    tags: ['short stories', 'interconnected', 'literary'],
    themes: ['memory', 'loss', 'meaning'],
    subjects: ['fiction', 'memory'],
    language: 'English',
    audience: 'Adult',
    publishedDate: new Date('2023-06-08'),
    price: 245,
    rating: 4.0,
    isPublished: true,
  },
];

const run = async () => {
  try {
    await mongoose.connect(mongoDBURL);
    console.log('✓ Connected to MongoDB');

    let createdCount = 0;
    for (const seedRecord of seedBooks) {
      await Book.findOneAndUpdate(
        { title: seedRecord.title, author: seedRecord.author },
        seedRecord,
        {
          returnDocument: 'after',
          upsert: true,
          runValidators: true,
          setDefaultsOnInsert: true,
        }
      );
      createdCount += 1;
    }

    console.log(`✓ Seed completed: ${createdCount} books upserted.`);
    await mongoose.connection.close();
  } catch (error) {
    console.error('✗ Seed error:', error.message);
    await mongoose.connection.close();
    process.exit(1);
  }
};

run();
